language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION scripted rpm/* debian/* universal/*
scala:
  - 2.10.3
jdk:
  - openjdk6
notifications:
  email:
    - qbranch@typesafe.com
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq rpm
