language: scala
os:
  - linux
script:
  - sbt ++$TRAVIS_SCALA_VERSION --warn update compile test:compile && sbt ++$TRAVIS_SCALA_VERSION test "scripted rpm/* debian/* universal/* jar/*"
scala:
  - 2.10.5
jdk:
  - openjdk7
  - oraclejdk8
notifications:
  email:
    - qbranch@typesafe.com
addons:
  apt:
    packages:
    - rpm
 
sudo: false
cache: 
 apt: true
 directories:
 - $HOME/.sbt
 - $HOME/.ivy2
