version: '{build}'
os: Windows Server 2012
install:
  - choco install sbt
build_script:
  - sbt clean compile
test_script:
  - sbt test
  - sbt "scripted windows/*"
cache:
  - C:\sbt\
  - C:\Users\appveyor\.m2
  - C:\Users\appveyor\.ivy2
