name: Validate PR

on: [pull_request]

jobs:
  validate:
    
    runs-on: [ macos, ubuntu-latest, windows ]
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v1
    - name: Set up Azul JDK 1.8 and SBT
      uses: olafurpg/setup-scala@v7
      with:
        java-version: zulu@1.8
    - name: Validate
      run: sbt "^validate"
  
  scripted-universal:
    runs-on: [ macos, ubuntu-latest, windows ]
    strategy:
      fail-fast: false
    needs: [ validate ]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Azul JDK 1.8 and SBT
      uses: olafurpg/setup-scala@v7
      with:
        java-version: zulu@1.8
    - name: Validate
      run: sbt "^validateUniversal
        
  scripted-jar:
    runs-on: [ macos, ubuntu-latest, windows ]
    strategy:
      fail-fast: false
    needs: [ validate ]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Azul JDK 1.8 and SBT
      uses: olafurpg/setup-scala@v7
      with:
        java-version: zulu@1.8
    - name: Validate
      run: sbt "^validateJar"       

  scripted-bash:
    runs-on: [ macos, ubuntu-latest ]
    strategy:
      fail-fast: false
    needs: [ validate ]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Azul JDK 1.8 and SBT
      uses: olafurpg/setup-scala@v7
      with:
        java-version: zulu@1.8
    - name: Validate
      run: sbt "^validateBash"

  scripted-ash:
    runs-on: [ macos, ubuntu-latest ]
    strategy:
      fail-fast: false
    needs: [ validate ]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Azul JDK 1.8 and SBT
      uses: olafurpg/setup-scala@v7
      with:
        java-version: zulu@1.8
    - name: Validate
      run: sbt "^validateAsh"


  scripted-rpm:
    runs-on: [ ubuntu-latest ]
    strategy:
      fail-fast: false
    needs: [ validate ]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Azul JDK 1.8 and SBT
      uses: olafurpg/setup-scala@v7
      with:
        java-version: zulu@1.8
    - name: Validate
      run: sbt "^validateRpm"

  scripted-debian:
    runs-on: [ ubuntu-latest ]
    strategy:
      fail-fast: false
    needs: [ validate ]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Azul JDK 1.8 and SBT
      uses: olafurpg/setup-scala@v7
      with:
        java-version: zulu@1.8
    - name: Validate
      run: sbt "^validateDebian"
        
  scripted-jdk-packager:
    runs-on: [ ubuntu-latest ]
    strategy:
      fail-fast: false
    needs: [ validate ]
    steps:
    - uses: actions/checkout@v1
    - name: Download JDK 1.8
      run: wget -O zulu-jdk.tar.gz https://cdn.azul.com/zulu/bin/zulu8.38.0.13-ca-fx-jdk8.0.212-linux_x64.tar.gz
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        # the standard zulu dist doesn't include javafx
        jdkFile: 'zulu-jdk.tar.gz'
    - name: Validate
      run: sbt "^validateJdkPackagerTravis"

  # FIXME github actions uses docker 3.0.8, which is too old for native-packager
  scripted-docker:
    runs-on: [ ubuntu-latest ]
    strategy:
      fail-fast: false
    needs: [ validate ]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Azul JDK 1.8 and SBT
      uses: olafurpg/setup-scala@v7
      with:
        java-version: zulu@1.8
    - name: Validate
      run: sbt "^validateDocker" "^validateDockerUnit"

  scripted-jlink:
    runs-on: [ ubuntu-latest ]
    strategy:
      fail-fast: false
    needs: [ validate ]
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11.0-2
      uses: olafurpg/setup-scala@v7
      with:
        java-version: zulu@1.11
    - name: Validate
      run: sbt "^validateJlink"
        

  scripted-graavlvm:
    runs-on: [ ubuntu-latest ]
    strategy:
      fail-fast: false
    needs: [ validate ]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Azul JDK 1.8 and SBT
      uses: olafurpg/setup-scala@v7
      with:
        java-version: zulu@1.8
    - name: Setup GraalVM environment
      uses: DeLaGuardo/setup-graalvm@2.0
      with:
        graalvm-version: '19.0.0.java8'
    - name: Install native-image
      run: gu install native-image
    - name: Validate
      run: sbt "^validateGraalVMNativeImage"

  scripted-osx:
    runs-on: [ macos ]
    strategy:
      fail-fast: false
    needs: [ validate ]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Azul JDK 1.8 and SBT
      uses: olafurpg/setup-scala@v7
      with:
        java-version: zulu@1.8
    - name: Validate
      run: sbt "^validateOSX"
        
  scripted-windows:
    runs-on: [ windows-latest ]
    strategy:
      fail-fast: false
    needs: [ validate ]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Azul JDK 1.8 and SBT
      uses: olafurpg/setup-scala@v7
      with:
        java-version: zulu@1.8
    - name: Validate
      run: sbt "^validateWindows"