name: Validate PR

on: [pull_request]

jobs:
  validate:
    
    runs-on: [ macos, ubuntu-latest, windows ] 

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Validate
      run: sbt "^validate"
  
  scripted-universal:
    runs-on: [ macos, ubuntu-latest, windows ]
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      with:
        java-version: 1.8
    - name: Validate
      run: sbt "^validateUniversal